baseURL: "https://www.abbymoreland.com/"
languageCode: "en-us"
title: "Abby Moreland"
theme: "PaperMod"

rssLimit: 10
author: 
  name: "Abby Moreland"

params:
    ShowCodeCopyButtons: true
    ShowPostNavLinks: true
    
    profileMode: 
        enabled: true
        title: "Abby Moreland" # optional default will be site title
        subtitle: "Technical writer, software documentation"
        imageUrl: "img/am.png" # optional
        imageTitle: "am logo" # optional
        imageWidth: 200 # custom size
        imageHeight: 200 # custom size  
        buttons:
          - name: About
            url: "/about"
          - name: Portfolio
            url: "/portfolio"
 #        - name: Resume
 #          url: "/resume"
          - name: Blog
            url: "/blog"
    defaultTheme: light
    disableThemeToggle: true
  

    socialIcons: # optional
          - name: "linkedin"
            url: "https://www.linkedin.com/in/abby-moreland/"
          - name: "github"
            url: "https://github.com/am-land"
          - name: "rss"
            url: "/rss"

    assets:
        favicon: "/img/favicon.ico"
        favicon16x16:  "/img/favicon-16x16.png"
        favicon32x32:  "/img/favicon-32x32.png"
        apple_touch_icon:  "/img/apple-touch-icon.png"
        safari_pinned_tab:  "/img/safari-pinned-tab.svg"

      
 #   cover:
 #     thumbnail: true
 #     thumbnailInList: true


outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

outputFormats:
  RSS:
    mediatype: "application/rss"
    baseName: "feed"

        
menu:
  main:
 # - identifier: home
 #   name: Home
 #   pre: <i class='fa fa-heart'></i>
 #   url: /
 #   weight: -110
 # - identifier: archive
 #   name: Archive
 #   pre: <i class='fa fa-heart'></i>
 #   url: /archive
  - identifier: portfolio
    name: Portfolio
    pre: <i class='fa fa-heart'></i>
    url: /portfolio
    weight: -110
#  - identifier: resume
#    name: Resume
#    pre: <i class='fa fa-heart'></i>
#    url: /resume
#    weight: -105    
  - identifier: blog
    name: Blog
    pre: <i class='fa fa-heart'></i>
    url: /blog
    weight: -100
  - identifier: categories
    name: Categories
    pre: <i class='fa fa-heart'></i>
    url: /categories
    weight: -90
  - identifier: search
    name: Search
    pre: <i class='fa fa-heart'></i>
    url: /search
    weight: -80
  - identifier: contact
    name: Contact
    url: /contact/

security:
  enableInlineShortcodes: false
  exec:
    osEnv:
      - (?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM|GEM_PATH)$
    allow:
      - ^dart-sass-embedded$
      - ^go$
      - ^npx$
      - ^postcss$
      - ^asciidoctor$

  funcs:
    getenv:
    - ^HUGO_
  http:
    methods:
    - (?i)GET|POST
    urls:
    - .*
